version: "3.8"

services:

  postgres:
    container_name: database
    image: postgres:17.2
    user: postgres
    ports:
      - 5432:5432
    networks:
      internal:
        ipv4_address: 172.20.0.2
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    container_name: database-admin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 15432:80
    networks:
      internal:
        ipv4_address: 172.20.0.3
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
  
  backend:
    container_name: backend-api-gateway
    build: 
      context: https://github.com/FEFU-ILPS/backend-api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8061:8061
    networks:
      internal:
        ipv4_address: 172.20.0.4
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8061/health"]
      interval: 10s
      timeout: 5s
      retries: 10



networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local